"""Initial: Create Articulo

Revision ID: 38fe8248b6b1
Revises: 
Create Date: 2026-09-17 22:57:00.071700

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fe8248b6b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulo')
    # ### end Alembic commands ###
