"""Create Table Proveedor

Revision ID: 4eb079d91d79
Revises: 6ead5e3cbca9
Create Date: 2026-09-24 22:27:59.801473

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb079d91d79'
down_revision: Union[str, Sequence[str], None] = '6ead5e3cbca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    # ### end Alembic commands ###
