"""add proveedor to Articulo

Revision ID: 6ead5e3cbca9
Revises: 38fe8248b6b1
Create Date: 2026-09-17 23:03:38.312819

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ead5e3cbca9'
down_revision: Union[str, Sequence[str], None] = '38fe8248b6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_column('proveedor')

    # ### end Alembic commands ###
